USE FLIGHTS19;

CREATE TABLE FLIGHTS19 (
    ROUTE CHAR(7),
    MON INT,
    CARRIER CHAR(2),
    DEP CHAR(3),
    DEPST CHAR(2),
    ARR CHAR(3),
    DELAY INT,
    FLIGHTS INT
);


# SHOW HOW THE DATA IS STORED IN THE TABLE. 

SELECT 
	*
FROM
	FLIGHTS19
LIMIT 20;
   
   
# SHOW EVERY ROUTE IN THE US AND HOW MANY FLIGHTS EACH CARRIER OPERATES EVERY MONTH.    
    
SELECT 
	ROUTE,
    CARRIER,
    SUM(FLIGHTS) as FLIGHTS
FROM
	FLIGHTS19
GROUP BY 
	ROUTE, CARRIER;
   
   
# SHOW THE TOP 30 AIRPORTS IN US BY NUMBER OF NATIONAL FLIGHTS DEPARTING THROUGHOUT THE YEAR.

SELECT
	DEP,
    SUM(FLIGHTS) as FLIGHTS
FROM
	FLIGHTS19
GROUP BY
	DEP
ORDER BY 2 DESC
LIMIT 30;
    
    
# SHOW THE CARRIERS ORDERED BY FLIGHTS OPERATED    
    
SELECT
	CARRIER,
    SUM(FLIGHTS) as FLIGHTS
FROM
	FLIGHTS19
GROUP BY
	CARRIER
ORDER BY 2 DESC;


# FIND OUT WHICH ARE THE 30 BUSIEST AIRPORTS AT A NATIONAL LEVEL.

SELECT
	DEP AS AIRPORT
FROM
	FLIGHTS19
GROUP BY 1
ORDER BY 2 DESC
LIMIT 30;


# SHOW THE ROUTES AMONG THE 30 BUSIEST AIRPORTS AND THE AMOUNT OF FLIGHTS OPERATING EACH OF THE ROUTES.

SELECT 
	ROUTE,
    SUM(FLIGHTS) as FLIGHTS
FROM
	FLIGHTS19
WHERE 
	DEP IN (
		SELECT
			DEP AS AIRPORT
		FROM
			FLIGHTS19
		GROUP BY 1
		HAVING SUM(FLIGHTS) > 75000
		)
	AND ARR IN (
		SELECT
			DEP AS AIRPORT
		FROM
			FLIGHTS19
		GROUP BY 1
		HAVING SUM(FLIGHTS) > 75000
		)
GROUP BY 
	ROUTE
ORDER BY 2 DESC;
